[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "arxiv-catchup"
description = "Searches arXiv for all papers since the previous execution. All papers with keyword/author matches from a pre-defined list are then opened in a web browser."
version = "1.8.0"
dependencies = ["certifi", "pylatexenc", "PyYAML", "unidecode"]
requires-python = ">=3.10"
authors = [{ name = "Peter Marinos", email = "peter_marinos@hotmail.com.au" }]
readme = "README.md"
license = { file = "LICENCE" }

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "pylint", "mypy", "types-PyYAML", "black"]
gui = ["customtkinter"]

[project.scripts]
arxiv-catchup = "arxiv_catchup.__main__:main"

[project.gui-scripts]
arxiv-catchup-gui = "arxiv_catchup.gui.__main__:main"

[project.urls]
Homepage = "https://github.com/petermarinos/arXiv_Catchup.git"
Repository = "https://github.com/petermarinos/arXiv_Catchup.git"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.mypy]
[[tool.mypy.overrides]]
module = ["pylatexenc.*", "customtkinter.*"]
ignore_missing_imports = true
