"""Small script used for type checking."""

# As this is just for duck typing, there should be no docstrings for the methods.
# Disable the pylint warning for this file.
# pylint: disable=missing-function-docstring

from __future__ import annotations
from typing import Protocol


class GuiActions(Protocol):
    """Define a protocol for all the elements in the GUI that the user can interact with."""

    def on_refresh(self) -> None: ...
    def on_toggle_keep_temp(self) -> None: ...
    def on_toggle_new_window(self) -> None: ...
    def on_check_dates(self) -> None: ...
    def on_search_info(self) -> None: ...
    def on_download(self) -> None: ...
    def on_score(self) -> None: ...
    def on_filter(self) -> None: ...
    def on_open(self) -> None: ...
    def on_write(self) -> None: ...
